codecov:
  token: d006bed5-f698-4007-b95f-58e8b21f8ba3
  notify:
    after_n_builds: 12

comment:
  after_n_builds: 12

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths:
          - "tests/"
        target: 100%
      source:
        paths:
          - "jupytext/"
        target: 97%
        threshold: 0.002
    patch:
      default:
        target: 80%  # new contributions should have a coverage at least equal to target
